<?php

namespace AlgoliaIndex\Helper;

class Index
{

    private static $_index = null; 

    /**
     * Get the index
     *
     * @return void
     */
    public static function getIndex() {
        
        //Used cached instance
        if(!is_null(self::$_index)) {
            return self::$_index;
        }

        //Connect to account
        $client = \Algolia\AlgoliaSearch\SearchClient::create(
            ALGOLIAINDEX_APPLICATION_ID,
            ALGOLIAINDEX_API_KEY
        );

        //Select index
        return self::$_index = $client->initIndex(self::getIndexName());
    }

    /**
     * Automatically create a index name, if not set by the developer. 
     * 
     *  - Index name will be the hostname as default.
     *  - 
     *
     * @return void
     */
    public static function getIndexName() {

        //Use user defined name
        if(defined('ALGOLIAINDEX_INDEX_NAME') && !empty(ALGOLIAINDEX_INDEX_NAME)) {
            return ALGOLIAINDEX_INDEX_NAME; 
        }

        //Use autogenerated index name, mutisites using subfolder structure will use the same index by default. 
        return str_replace(".", "-", parse_url(get_option('home'))['host']);
    }
    
}
