name: PHP CS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHP CS Fixer
        uses: StephaneBour/actions-php-cs-fixer@1.0
        with:
          # Fix php
          dir: 'source/'

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          # Folder to check code style
          dir: source/